version: '3.8'
services:
  web:
    image: ghcr.io/yju-okura/minori_gin:latest
    ports:
      - "80:8080"
    environment:
      - ENV_FILE=/volume/.env
    restart: always
    volumes:
      - /volume/.env:/path/inside/container