version: '3'

services:
  go:
    container_name: go
    build: docker/go/
    ports:
      - "8080:8080"
    links:
        - mysql
#        - redis
    tty:
      true
    volumes:
      - ./:/app
    working_dir: /app
  mysql:
    container_name: mysql
    build: ./docker/mysql/
    hostname: mysql
    ports:
      - "3306:3306"
    env_file:
      - docker/mysql/env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "./mysql_data/mysql:/var/lib/mysql"
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
      - "./docker/mysql/init/:/docker-entrypoint-initdb.d"