name: Deploy to EC2

on:
  workflow_run:
    workflows: ['Docker Image CI']  # Docker Image CI ワークフローが実行された後に実行
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | # 最新のイメージが実行中でない場合、EC2 インスタンスにデプロイ
            set -e
            sudo docker pull ghcr.io/yju-okura/minori_gin:latest
            sudo docker stop minori_gin || true
            sudo docker rm minori_gin || true
            sudo docker run -d --name minori_gin -p 80:8080 ghcr.io/yju-okura/minori_gin:latest
            echo "Deployment completed successfully"

      - name: Check deployment status
        run: |
          echo "Checking deployment status..."
          curl -sSf http://${{ secrets.EC2_HOST }}:80/healthz || echo "Health check failed."
