name: Docker Image CI

on:
  pull_request_target:
    types: [closed] # プルリクエストがクローズされたときに実行
    branches: [main]  # main ブランチに対してのみ実行

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      RUN_MIGRATIONS: ${{ secrets.RUN_MIGRATIONS }}
    if: contains(github.event.pull_request.labels.*.name, '🆗 safe') && github.event.pull_request.merged == true # 「🆗 safe」 ラベルがあり、マージされたプルリクエストに対してのみ実行

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run tests
        run: go test ./tests/...

      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            RUN_MIGRATIONS=${{ secrets.RUN_MIGRATIONS }}
          tags: |
            ghcr.io/yju-okura/minori_gin:${{ steps.date.outputs.date }}
            ghcr.io/yju-okura/minori_gin:latest